name: Run Known-Good Proofs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-proofs:
    runs-on: ubuntu-latest
    name: Check Proofs
    steps:
      - uses: actions/checkout@v2
      - name: Install CVC5
        run: sudo apt install cvc5

      - name: Build ssbee
        run: |
          cargo build --release -p ssbee
          echo "SSBEE=$(pwd)/target/release/ssbee">>$GITHUB_ENV

      - name: Run proofs
        run: |
          echo "# Checking Reproducers still prove..."
          for project_path in example-projects/repro-*; do
            project=$(basename $project_path)
            (
              echo "## Checking $project proves..."
              cd $project_path;
              $SSBEE prove
            )
          done

          echo "# Checking known-good proofs still prove..."
          while read project; do
            project_path=example-projects/$project
            # skip comments
            if [ ! -d $project_path ]; then
              echo "WARN: skipping non-existing project in known-good proofs: $project"
              continue
            fi
            (
              echo "## Checking $project proves..."
              cd $project_path;
              $SSBEE prove
            )
          done <example-projects/known-good.txt


